### ISSUE TITLE
Уточнить требования по списку проектов

### ISSUE THREAD

**Issue by AMaklakov** [vliplianina/scrum-team-2a#1]
Уточнить поведение при удалении последней записи для списка.

Возможные варианты:
Показ сообщения "Записей в таблице нет"

**Comment by AMaklakov** [comment]
Нужно ли как-либо помечать проекты, у которых нет сотрудников? 
Нужно ли помечать проекты,  у которых нету задач?

**Comment by AMaklakov** [comment]
Есть ли необходимость делать пагинацию или отложенную загрузку проектов когда их более 10?
А если более 20?

При каком количестве проектов надо отображать пагинацию или отложенную загрузку?

**Comment by AMaklakov** [comment]
Каким образом будет осуществляться сортировка проектов?
По id, по наименованию?

**Comment by AMaklakov** [comment]
При удалении проекта, что должно происходить с задачами, прикрепленными к этому проекту?
Должны ли они удаляться?

**Comment by AMaklakov** [comment]
Предусмотрена ли возможность для различных пользователей отображение не всех проектов, а только некоторых?

**Comment by vliplianina** [comment]
> Уточнить поведение при удалении последней записи для списка.
> 
> Возможные варианты:
> Показ сообщения "Записей в таблице нет"

см. issue #5 

> Нужно ли как-либо помечать проекты, у которых нет сотрудников?
> Нужно ли помечать проекты, у которых нету задач?

см. issue #6 



> Есть ли необходимость делать пагинацию или отложенную загрузку проектов когда их более 10?
> А если более 20?
> 
> При каком количестве проектов надо отображать пагинацию или отложенную загрузку?

Пагинация или отложенная загрузка не предусмотрены реализацией данной версии приложения. При тестировании оформите запрос на улучшение.


> Каким образом будет осуществляться сортировка проектов?
> По id, по наименованию?

По идентификатору


> При удалении проекта, что должно происходить с задачами, прикрепленными к этому проекту?
> Должны ли они удаляться?

Не должны удаляться


> Предусмотрена ли возможность для различных пользователей отображение не всех проектов, а только некоторых?

Реализация разграничений по ролям не предусмотрена текущей версией приложения


@AMaklakov 
Замечание по оформлению: 
нужно подобрать информативный заголовок данному запросу на уточнение требований
