### ISSUE TITLE
Создание и редактирование задачи: уточнить физические и логические ограничения на ввод в поля.

### ISSUE THREAD

**Issue by IvanShinkevich** [vliplianina/scrum-team-2a#13]
Создание и редактирование задачи: Уточнить физические и логические ограничения на ввод в следующие поля:
- Название
- Работа (часы)
- Дата начала
- Дата окончания
- Статус (Не начата | В процессе | Завершена | Отложена)

**Comment by vliplianina** [comment]
Уточнения добавлены в [требования](https://github.com/vliplianina/scrum-team-2a/blob/master/TrainingTask%20-%20Requirements.md) - см. п.6 "Форма ввода задачи"
