### ISSUE TITLE
Форма ввода сотрудника(исполнителя): уточнить физические и логические ограничения на ввод в поля

### ISSUE THREAD

**Issue by IvanShinkevich** [vliplianina/scrum-team-2a#15]
Форма создания и редактирования задачи: уточнить физические и логические ограничения на ввод в следующие поля:

- Фамилия
- Имя
- Отчество
- Должность

**Comment by vliplianina** [comment]
Уточнения добавлены в [требования](https://github.com/vliplianina/scrum-team-2a/blob/master/TrainingTask%20-%20Requirements.md): см. п. 7 "Форма ввода персоны"
