### ISSUE TITLE
Список задач - Уточнить реализацию перехода в режим редактирования задачи

### ISSUE THREAD

**Issue by kozant** [vliplianina/scrum-team-2a#20]
Возможные варианты:

1. Будет ли располагаться форма редактирования на отдельной странице?
2. Будет ли автоматически выделяться место для формы редактирования под командой "Изменить"?
3. Другой вариант.

**Comment by vliplianina** [comment]
Вариант 1:  по нажатию на кнопку "Изменить" осуществляется переход к форме редактирования задачи
