### ISSUE TITLE
Ввод задачи: Уточнить реализацию поля "Статус"

### ISSUE THREAD

**Issue by TimSeredinski** [vliplianina/scrum-team-2a#21]
Ручной ввод или же выбор из списка, другой вариант

**Comment by vliplianina** [comment]
Выбор из списка.
Уточнение добавлено в [требования](https://github.com/vliplianina/team-9b-volunteers/blob/master/TrainingTask%20-%20Requirements.md): см.п. 6 "Форма ввода задачи"
