### ISSUE TITLE
Ввод задачи: Уточнить реализацию поля "Работа"

### ISSUE THREAD

**Issue by TimSeredinski** [vliplianina/scrum-team-2a#22]
Возможно ли оставить поле пустым, с расчетом на заполнение в будущем или же обязательно к заполнению при создании.

**Comment by vliplianina** [comment]
Поле обязательно для заполнения.
Уточнение добавлено в [требования](https://github.com/vliplianina/team-9b-volunteers/blob/master/TrainingTask%20-%20Requirements.md): см.п. 6 "Форма ввода задачи"
