### ISSUE TITLE
Создание и редактирование сотрудника: Уточнить ограничение на алфавиты на ввод в поля

### ISSUE THREAD

**Issue by Ageenkooo** [vliplianina/scrum-team-2a#27]

**Comment by vliplianina** [comment]
Допустимы латиница [A-z] и кириллица [А-я].
Уточнения добавлены в [требования](https://github.com/vliplianina/scrum-team-2a/blob/master/TrainingTask%20-%20Requirements.md): см. п. 7. "Форма ввода персоны"
