### ISSUE TITLE
Создание и редактирование сотрудника: Уточнить валидацию на ввод

### ISSUE THREAD

**Issue by Ageenkooo** [vliplianina/scrum-team-2a#31]

**Comment by vliplianina** [comment]
Общий вопрос - общий ответ: обязательные поля должны быть заполнены допустимыми значениями.
Требования к валидации каждого из полей см. в [требованиях](https://github.com/vliplianina/scrum-team-2a/blob/master/TrainingTask%20-%20Requirements.md) п. 7. "Форма ввода персоны"
