### ISSUE TITLE
Уточнение требований для формы "Список сотрудников"

### ISSUE THREAD

**Issue by ArtimenyaEgor** [vliplianina/scrum-team-2a#32]
1. Какие поля являются редактируемыми, а какие нет?
2. Какие символы можно и регистр использовать в текстовых полях?
3. Какая длина у текстовых полей?
4. Всегда ли кнопки видны и всегда ли они enabled?
5. Добавить описания случаев, когда какие-то поля слишком большие для отображения.
6. Добавить информацию о том, как отображать большое количество записей.
7. Что должен видеть пользователь, если еще не создано ни одной записи сотрудников?
8. Разрешено ли где-то оставлять поля пустыми?
9. Можно ли использовать цифры или спецсимволы в тестовых полях?

**Comment by vliplianina** [comment]
1. Все поля редактируемые, кроме поля "Идентификатор"
2. латиница [A-z], кириллица [А-я]
3.
