### ISSUE TITLE
Форма ввода проекта. Уточнить ограничения на редактируемые поля.

### ISSUE THREAD

**Issue by shutilin** [vliplianina/scrum-team-2a#7]
Необходимы ограничения на следующие поля:
- Название
- Сокращенное название
- Описание

**Comment by vliplianina** [comment]
Уточнение добавлены [требования](https://github.com/vliplianina/scrum-team-2a/blob/master/TrainingTask%20-%20Requirements.md): см.п. 5 "Форма ввода проекта"
